class Idioma:

    ATUAL = "pt"

    TEXTOS = {
        "pt": {

            # Comuns a várias telas
            "comum.id": "ID",
            "comum.nome": "Nome",
            "comum.novo": "Novo",
            "comum.salvar": "Salvar",
            "comum.alterar": "Alterar",
            "comum.excluir": "Excluir",
            "comum.fechar": "Fechar",
            "comum.cancelar": "Cancelar",
            "comum.confirmacao": "Confirmação",
            "comum.erro_prefixo": "Erro: ",

            # Tela de Estados
            "estado.janela_titulo": "CRUD de Estados",
            "estado.titulo": "Cadastro de Estados",
            "estado.dados_frame": "Dados do estado",
            "estado.sigla": "Sigla",
            "estado.confirmar_exclusao": "Deseja realmente excluir este estado?",
            "estado.cadastrado_sucesso": "Estado cadastrado com sucesso!",
            "estado.atualizado_sucesso": "Estado atualizado com sucesso!",
            "estado.excluido_sucesso": "Estado excluído com sucesso!",
            "estado.nao_encontrado": "Estado não encontrado.",
            "estado.selecione_da_lista": "Selecione um estado na lista.",
            "estado.erro_ao_excluir": "Problemas ao excluir estado",
            "estado.erro_sigla_tamanho": "A sigla deve possuir exatamente 2 caracteres.",

            # Tela de Cidades
            "cidade.janela_titulo": "CRUD de Cidades",
            "cidade.titulo": "Cadastro de Cidades",
            "cidade.dados_frame": "Dados da cidade",
            "cidade.estado": "Estado",
            "cidade.nome": "Nome",
            "cidade.confirmar_exclusao": "Deseja realmente excluir esta cidade?",
            "cidade.cadastrado_sucesso": "Cidade cadastrada com sucesso!",
            "cidade.atualizado_sucesso": "Cidade atualizada com sucesso!",
            "cidade.excluido_sucesso": "Cidade excluída com sucesso!",
            "cidade.nao_encontrado": "Cidade não encontrada.",
            "cidade.selecione_da_lista": "Selecione uma cidade na lista.",
            "cidade.erro_ao_excluir": "Problemas ao excluir cidade",
            "cidade.erro_nome_vazio": "O nome da cidade não pode ficar vazio.",
            "cidade.erro_estado_nao_selecionado": "Selecione um estado para a cidade.",

            # Tela de Usuário
            "usuario.janela_titulo": "CRUD de Usuários",
            "usuario.titulo": "Cadastro de Usuários",
            "usuario.dados_frame": "Dados do usuário",
            "usuario.nome": "Nome",
            "usuario.email": "Email",
            "usuario.nascimento": "Nascimento",
            "usuario.idade": "Idade",
            "usuario.cidade": "Cidade",
            "usuario.uf": "UF",
            "usuario.perfil": "Perfil",
            "usuario.erro_cidade_nao_selecionado": "Selecione uma cidade para o usuário.",
            "usuario.erro_estado_nao_selecionado": "Selecione um estado para o usuário.",
            "usuario.erro_perfil_nao_selecionado": "Selecione um perfil para o usuário.",
            "usuario.erro_data_invalida": "Data de nascimento inválida. Use o formato DD/MM/AAAA.",
            "usuario.confirmar_exclusao": "Deseja realmente excluir este usuário?",
            "usuario.cadastrado_sucesso": "Usuário cadastrado com sucesso!",
            "usuario.atualizado_sucesso": "Usuário atualizado com sucesso!",
            "usuario.excluido_sucesso": "Usuário excluído com sucesso!",
            "usuario.nao_encontrado": "Usuário não encontrado.",
            "usuario.selecione_da_lista": "Selecione um usuário na lista.",
            "usuario.erro_ao_excluir": "Problemas ao excluir usuário",
            "usuario.erro_nome_vazio": "O nome do usuário não pode ficar vazio.",
            "usuario.erro_email_vazio": "O email do usuário não pode ficar vazio.",

            # Tela de perfil
            "perfil.janela_titulo": "CRUD de Perfis",
            "perfil.titulo": "Cadastro de Perfis",
            "perfil.dados_frame": "Dados do perfil",
            "perfil.nome": "Nome",
            "perfil.descricao": "Descrição",
            "perfil.confirmar_exclusao": "Deseja realmente excluir este perfil?",
            "perfil.cadastrado_sucesso": "Perfil cadastrado com sucesso!",
            "perfil.atualizado_sucesso": "Perfil atualizado com sucesso!",
            "perfil.excluido_sucesso": "Perfil excluído com sucesso!",
            "perfil.nao_encontrado": "Perfil não encontrado.",
            "perfil.selecione_da_lista": "Selecione um perfil na lista.",
            "perfil.erro_ao_excluir": "Problemas ao excluir perfil",
            "perfil.erro_nome_vazio": "O nome do perfil não pode ficar vazio.",
            "perfil.erro_descricao_vazio": "A descrição do perfil não pode ficar vazia.",

            # Tela de clietes
            "cliente.janela_titulo": "CRUD de Clientes",
            "cliente.titulo": "Cadastro de Clientes",
            "cliente.dados_frame": "Dados do cliente",
            "cliente.nome": "Nome",
            "cliente.limite_credito": "Limite de crédito",
            "cliente.nascimento": "Nascimento",
            "cliente.cidade_nao_selecionado": "Erro ao cadastrar cliente: selecione uma cidade.",
            "cliente.estado_nao_selecionado": "Erro ao cadastrar cliente: selecione um estado.",
            "cliente.erro_data_invalida": "Erro ao cadastrar cliente: data de nascimento inválida. Use o formato DD/MM/AAAA.",
            "cliente.confirmar_exclusao": "Deseja realmente excluir este cliente?",
            "cliente.cadastrado_sucesso": "Cliente cadastrado com sucesso!",
            "cliente.atualizado_sucesso": "Cliente atualizado com sucesso!",
            "cliente.excluido_sucesso": "Cliente excluído com sucesso!",
            "cliente.nao_encontrado": "Cliente não encontrado.",    
            "cliente.selecione_da_lista": "Selecione um cliente na lista.",
            "cliente.erro_ao_excluir": "Problemas ao excluir cliente",
            "ciiente.erro_nome_vazio": "O nome não pode ficar vazio",
            "cliente.erro_limite_credito ": "O limite de credito não pode ser negativo",
            "cliente.erro_data_nascimento_vazio" : "A data de nascimento não pode ficar vazia", 

            # Tela de produtos
            "produto.janela_titulo" : "CRUD de produtos",
            "produto.titulo" : "Cadastro de Produtos",
            "produto.dados_frame" : "Dados do produto",
            "produto.nome" : "Nome",
            "produto.preco" : "Preço",
            "produto.fornecedor_nao_selecionado" : "Erro ao cadastrar produto: selecione um fornecedor.",
            "produto.estoque" : "Estoque",
            "produto.confirmar_exclusao" : "Deseja realmente excluir este produto?",
            "produto.cadastro_sucesso" : "Produto cadastrado com sucesso!",
            "Produto.atualizado_sucesso": "Produto atualizado com sucesso!",
            "produto.excluido_sucesso": "Produto excluído com sucesso!",
            "Produto.nao_encontrado": "Produto não encontrado.",    
            "Produto.selecione_da_lista": "Selecione um cliente na lista.",
            "Produto.erro_ao_excluir": "Problemas ao excluir cliente",
            "Produto.erro_nome_vazio": "O nome não pode ficar vazio",
            
            # Tela de fornecedor
            "fornecedor.janela_titulo" : "CRUD de fornecedor",
            "fornecedor.titulo" : "Cadastro de Fornecedor",
            "fornecedor.dados_frame" : "Dados do fornecedor",
            "fornecedor.nome" : "Nome fantasia",
            "fornecedor.razao_social" : "Razão soacial",
            "fornecedor.cnpj" : "CNPJ",
            "fornecedor.sla_atendimento" : "SLA de atendimento",
            "fornecedor.confirmar_exclusao" : "Deseja realmente excluir este fornecedor?",
            "fornecedor.cadastro_sucesso" : "Fornecedor cadastrado com sucesso!",
            "fornecedor.atualizado_sucesso": "Fornecedor atualizado com sucesso!",
            "fornecedor.excluido_sucesso": "Fornecedor excluído com sucesso!",
            "fornecedor.nao_encontrado": "Fornecedor não encontrado.",    
            "fornecedor.selecione_da_lista": "Selecione um fornecedor na lista.",
            "fornecedor.erro_ao_excluir": "Problemas ao excluir fornecedor",
            "fornecedor.sla_erro_negativo" : "O fornesedor não pode ter um SLA negativo.",
        
            
            
            # Tela de categoria
            "categoria.janela_titulo" : "CRUD de categoria",
            "categoria.titulo" : "Cadastro de Categorias",
            "categoria.dados_frame" : "Dados da categoria",
            "categoria.nome" : "Nome",
            "categoria.confirmar_exclusao" : "Deseja realmente excluir este categoria?",
            "categoria.cadastro_sucesso" : "Categoria cadastrado com sucesso!",
            "categoria.atualizado_sucesso": "Categoria atualizado com sucesso!",
            "categoria.excluido_sucesso": "Categoria excluído com sucesso!",
            "categoria.nao_encontrado": "Categoria não encontrado.",    
            "categoria.selecione_da_lista": "Selecione um categoria na lista.",
            "categoria.erro_ao_excluir": "Problemas ao excluir categoria",
            "categoria.erro_nome_vazio" : "O nome não pode ficar vazio.",
            
            # Menu principal
            "menu.cadastros_basicos": "Cadastros básicos",
            "menu.estados": "Estados",
            "menu.cidades": "Cidades",
            "menu.acessos": "Acessos",
            "menu.usuarios": "Usuários",
            "menu.perfis": "Perfis",
            "menu.gestao_estoque": "Gestão de estoque",
            "menu.clientes": "Clientes",
            "menu.fornecedores": "Fornecedores",
            "menu.produtos": "Produtos",
            "menu.categorias": "Categorias",
            "menu.idioma": "Idioma",
            "menu.sair": "Sair",
        },
        "en": {

            # Common to several screens
            "comum.id": "ID",
            "comum.nome": "Name",
            "comum.novo": "New",
            "comum.salvar": "Save",
            "comum.alterar": "Edit",
            "comum.excluir": "Delete",
            "comum.fechar": "Close",
            "comum.cancelar": "Cancel",
            "comum.confirmacao": "Confirmation",
            "comum.erro_prefixo": "Error: ",

            # States screen
            "estado.janela_titulo": "State Management",
            "estado.titulo": "State Registration",
            "estado.dados_frame": "State data",
            "estado.sigla": "Abbreviation",
            "estado.confirmar_exclusao": "Do you really want to delete this state?",
            "estado.cadastrado_sucesso": "State registered successfully!",
            "estado.atualizado_sucesso": "State updated successfully!",
            "estado.excluido_sucesso": "State deleted successfully!",
            "estado.nao_encontrado": "State not found.",
            "estado.selecione_da_lista": "Select a state from the list.",
            "estado.erro_ao_excluir": "Problem deleting state",
            "estado.erro_sigla_tamanho": "The abbreviation must have exactly 2 characters.",

            # Cities screen
            "cidade.janela_titulo": "City Management",
            "cidade.titulo": "City Registration",
            "cidade.dados_frame": "City data",
            "cidade.estado": "State",
            "cidade.nome": "Name",
            "cidade.confirmar_exclusao": "Do you really want to delete this city?",
            "cidade.cadastrado_sucesso": "City registered successfully!",
            "cidade.atualizado_sucesso": "City updated successfully!",
            "cidade.excluido_sucesso": "City deleted successfully!",
            "cidade.nao_encontrado": "City not found.",
            "cidade.selecione_da_lista": "Select a city from the list.",
            "cidade.erro_ao_excluir": "Problem deleting city",
            "cidade.erro_nome_vazio": "The city name cannot be empty.",
            "cidade.erro_estado_nao_selecionado": "Select a state for the city.",

            # Users screen
            "usuario.janela_titulo": "User Management",
            "usuario.titulo": "User Registration",
            "usuario.dados_frame": "User data",
            "usuario.nome": "Name",
            "usuario.email": "Email",
            "usuario.nascimento": "Date of birth",
            "usuario.idade": "Age",
            "usuario.cidade": "City",
            "usuario.uf": "State",
            "usuario.perfil": "Role",
            "usuario.erro_cidade_nao_selecionado": "Select a city for the user.",
            "usuario.erro_estado_nao_selecionado": "Select a state for the user.",
            "usuario.erro_perfil_nao_selecionado": "Select a role for the user.",
            "usuario.erro_data_invalida": "Invalid date of birth. Use the DD/MM/YYYY format.",
            "usuario.confirmar_exclusao": "Do you really want to delete this user?",
            "usuario.cadastrado_sucesso": "User registered successfully!",
            "usuario.atualizado_sucesso": "User updated successfully!",
            "usuario.excluido_sucesso": "User deleted successfully!",
            "usuario.nao_encontrado": "User not found.",
            "usuario.selecione_da_lista": "Select a user from the list.",
            "usuario.erro_ao_excluir": "Problem deleting user",
            "usuario.erro_nome_vazio": "The user name cannot be empty.",
            "usuario.erro_email_vazio": "The user email cannot be empty.",

            # Profile screen
            "perfil.janela_titulo": "Profile CRUD",
            "perfil.titulo": "Profile Registration",
            "perfil.dados_frame": "Profile Data",
            "perfil.nome": "Name",
            "perfil.descricao": "Description",
            "perfil.confirmar_exclusao": "Do you really want to delete this profile?",
            "perfil.cadastrado_sucesso": "Profile registered successfully!",
            "perfil.atualizado_sucesso": "Profile updated successfully!",
            "perfil.excluido_sucesso": "Profile deleted successfully!",
            "perfil.nao_encontrado": "Profile not found.",
            "perfil.selecione_da_lista": "Select a profile from the list.",
            "perfil.erro_ao_excluir": "Problems deleting profile",
            "perfil.erro_nome_vazio": "The profile name cannot be empty.",
            "perfil.erro_descricao_vazio": "The profile description cannot be empty.",
            
            # Client screen
            "cliente.janela_titulo": "Client CRUD",
            "cliente.titulo": "Client Registration",
            "cliente.dados_frame": "Client Data",
            "cliente.nome": "Name",
            "cliente.limite_credito": "Credit Limit",
            "cliente.nascimento": "Date of Birth",
            "cliente.cidade_nao_selecionado": "Error registering client: select a city.",
            "cliente.estado_nao_selecionado": "Error registering client: select a state.",
            "cliente.erro_data_invalida": "Error registering client: invalid date of birth. Use the format DD/MM/YYYY.",
            "cliente.confirmar_exclusao": "Do you really want to delete this client?",
            "cliente.cadastrado_sucesso": "Client registered successfully!",
            "cliente.atualizado_sucesso": "Client updated successfully!",
            "cliente.excluido_sucesso": "Client deleted successfully!",
            "cliente.nao_encontrado": "Client not found.",
            "cliente.selecione_da_lista": "Select a client from the list.",
            "cliente.erro_ao_excluir": "Problems deleting client",
            "ciiente.erro_nome_vazio": "The name cannot be empty",
            "cliente.erro_limite_credito": "The credit limit cannot be negative",
            "cliente.erro_data_nascimento_vazio": "The date of birth cannot be empty",


            # Product screen
            "produto.janela_titulo": "Product CRUD",
            "produto.titulo": "Product Registration",
            "produto.dados_frame": "Product Data",
            "produto.nome": "Name",
            "produto.preco": "Price",
            "produto.fornecedor_nao_selecionado": "Error registering product: select a supplier.",
            "produto.estoque": "Stock",
            "produto.confirmar_exclusao": "Do you really want to delete this product?",
            "produto.cadastro_sucesso": "Product registered successfully!",
            "Produto.atualizado_sucesso": "Product updated successfully!",
            "produto.excluido_sucesso": "Product deleted successfully!",
            "Produto.nao_encontrado": "Product not found.",
            "Produto.selecione_da_lista": "Select a product from the list.",
            "Produto.erro_ao_excluir": "Problems deleting product",
            "Produto.erro_nome_vazio": "The name cannot be empty",
            
            # Supplier screen
            "fornecedor.janela_titulo": "Supplier CRUD",
            "fornecedor.titulo": "Supplier Registration",
            "fornecedor.dados_frame": "Supplier Data",
            "fornecedor.nome": "Trade Name",
            "fornecedor.razao_social": "Legal Name",
            "fornecedor.cnpj": "CNPJ",
            "fornecedor.sla_atendimento": "Service SLA",
            "fornecedor.confirmar_exclusao": "Do you really want to delete this supplier?",
            "fornecedor.cadastro_sucesso": "Supplier registered successfully!",
            "fornecedor.atualizado_sucesso": "Supplier updated successfully!",
            "fornecedor.excluido_sucesso": "Supplier deleted successfully!",
            "fornecedor.nao_encontrado": "Supplier not found.",
            "fornecedor.selecione_da_lista": "Select a supplier from the list.",
            "fornecedor.erro_ao_excluir": "Problems deleting supplier",
            "fornecedor.sla_erro_negativo": "The supplier cannot have a negative SLA.",

            # Category screen
            "categoria.janela_titulo": "Category CRUD",
            "categoria.titulo": "Category Registration",
            "categoria.dados_frame": "Category Data",
            "categoria.nome": "Name",
            "categoria.confirmar_exclusao": "Do you really want to delete this category?",
            "categoria.cadastro_sucesso": "Category registered successfully!",
            "categoria.atualizado_sucesso": "Category updated successfully!",
            "categoria.excluido_sucesso": "Category deleted successfully!",
            "categoria.nao_encontrado": "Category not found.",
            "categoria.selecione_da_lista": "Select a category from the list.",
            "categoria.erro_ao_excluir": "Problems deleting category",
            "categoria.erro_nome_vazio": "The name cannot be empty.",
            
            # Main menu
            "menu.cadastros_basicos": "Basic registrations",
            "menu.estados": "States",
            "menu.cidades": "Cities",
            "menu.acessos": "Access",
            "menu.usuarios": "Users",
            "menu.perfis": "Roles",
            "menu.gestao_estoque": "Inventory management",
            "menu.clientes": "Customers",
            "menu.fornecedores": "Suppliers",
            "menu.produtos": "Products",
            "menu.categorias": "Categories",
            "menu.idioma": "Language",
            "menu.sair": "Exit",
        }
    }

    @classmethod
    def definir(cls, codigo):
        cls.ATUAL = codigo

    @classmethod
    def t(cls, chave):
        return cls.TEXTOS[cls.ATUAL].get(chave, chave)