class Idioma:

    ATUAL = "pt"

    TEXTOS = {
        "pt": {

            # Comuns a várias telas
            "comum.id": "ID",
            "comum.nome": "Nome",
            "comum.novo": "Novo",
            "comum.salvar": "Salvar",
            "comum.alterar": "Alterar",
            "comum.excluir": "Excluir",
            "comum.fechar": "Fechar",
            "comum.cancelar": "Cancelar",
            "comum.confirmacao": "Confirmação",
            "comum.erro_prefixo": "Erro: ",

            # Tela de Estados
            "estado.janela_titulo": "CRUD de Estados",
            "estado.titulo": "Cadastro de Estados",
            "estado.dados_frame": "Dados do estado",
            "estado.sigla": "Sigla",
            "estado.confirmar_exclusao": "Deseja realmente excluir este estado?",
            "estado.cadastrado_sucesso": "Estado cadastrado com sucesso!",
            "estado.atualizado_sucesso": "Estado atualizado com sucesso!",
            "estado.excluido_sucesso": "Estado excluído com sucesso!",
            "estado.nao_encontrado": "Estado não encontrado.",
            "estado.selecione_da_lista": "Selecione um estado na lista.",
            "estado.erro_ao_excluir": "Problemas ao excluir estado",
            "estado.erro_sigla_tamanho": "A sigla deve possuir exatamente 2 caracteres.",

            # Tela de Cidades
            "cidade.janela_titulo": "CRUD de Cidades",
            "cidade.titulo": "Cadastro de Cidades",
            "cidade.dados_frame": "Dados da cidade",
            "cidade.estado": "Estado",
            "cidade.nome": "Nome",
            "cidade.confirmar_exclusao": "Deseja realmente excluir esta cidade?",
            "cidade.cadastrado_sucesso": "Cidade cadastrada com sucesso!",
            "cidade.atualizado_sucesso": "Cidade atualizada com sucesso!",
            "cidade.excluido_sucesso": "Cidade excluída com sucesso!",
            "cidade.nao_encontrado": "Cidade não encontrada.",
            "cidade.selecione_da_lista": "Selecione uma cidade na lista.",
            "cidade.erro_ao_excluir": "Problemas ao excluir cidade",
            "cidade.erro_nome_vazio": "O nome da cidade não pode ficar vazio.",
            "cidade.erro_estado_nao_selecionado": "Selecione um estado para a cidade.",

            # Tela de Usuário
            "usuario.janela_titulo": "CRUD de Usuários",
            "usuario.titulo": "Cadastro de Usuários",
            "usuario.dados_frame": "Dados do usuário",
            "usuario.nome": "Nome",
            "usuario.email": "Email",
            "usuario.nascimento": "Nascimento",
            "usuario.idade": "Idade",
            "usuario.cidade": "Cidade",
            "usuario.uf": "UF",
            "usuario.perfil": "Perfil",
            "usuario.erro_cidade_nao_selecionado": "Selecione uma cidade para o usuário.",
            "usuario.erro_estado_nao_selecionado": "Selecione um estado para o usuário.",
            "usuario.erro_perfil_nao_selecionado": "Selecione um perfil para o usuário.",
            "usuario.erro_data_invalida": "Data de nascimento inválida. Use o formato DD/MM/AAAA.",
            "usuario.confirmar_exclusao": "Deseja realmente excluir este usuário?",
            "usuario.cadastrado_sucesso": "Usuário cadastrado com sucesso!",
            "usuario.atualizado_sucesso": "Usuário atualizado com sucesso!",
            "usuario.excluido_sucesso": "Usuário excluído com sucesso!",
            "usuario.nao_encontrado": "Usuário não encontrado.",
            "usuario.selecione_da_lista": "Selecione um usuário na lista.",
            "usuario.erro_ao_excluir": "Problemas ao excluir usuário",
            "usuario.erro_nome_vazio": "O nome do usuário não pode ficar vazio.",
            "usuario.erro_email_vazio": "O email do usuário não pode ficar vazio.",

            # Tela de Perfis
            "perfil.janela_titulo": "CRUD de Perfis",
            "perfil.titulo": "Cadastro de Perfis",
            "perfil.dados_frame": "Dados do perfil",
            "perfil.descricao": "Descrição",
            "perfil.fornecedores": "Fornecedores",
            "perfil.confirmar_exclusao": "Deseja realmente excluir este perfil?",
            "perfil.cadastrado_sucesso": "Perfil cadastrado com sucesso!",
            "perfil.atualizado_sucesso": "Perfil atualizado com sucesso!",
            "perfil.excluido_sucesso": "Perfil excluído com sucesso!",
            "perfil.nao_encontrado": "Perfil não encontrado.",
            "perfil.selecione_da_lista": "Selecione um perfil na lista.",
            "perfil.erro_ao_excluir": "Problemas ao excluir perfil",
            "perfil.sem_fornecedores": "Cadastre fornecedores antes de associá-los a um perfil.",
            "perfil.fornecedores_atualizados_sucesso": "Fornecedores do perfil atualizados com sucesso!",
            "perfil.erro_salvar_fornecedores": "Não foi possível salvar os fornecedores do perfil.",

            # Tela de Clientes
            "cliente.janela_titulo": "CRUD de Clientes",
            "cliente.titulo": "Cadastro de Clientes",
            "cliente.dados_frame": "Dados do cliente",
            "cliente.nascimento": "Nascimento",
            "cliente.idade": "Idade",
            "cliente.limite_credito": "Limite de crédito",
            "cliente.cidade": "Cidade",
            "cliente.uf": "UF",
            "cliente.confirmar_exclusao": "Deseja realmente excluir este cliente?",
            "cliente.cadastrado_sucesso": "Cliente cadastrado com sucesso!",
            "cliente.atualizado_sucesso": "Cliente atualizado com sucesso!",
            "cliente.excluido_sucesso": "Cliente excluído com sucesso!",
            "cliente.nao_encontrado": "Cliente não encontrado.",
            "cliente.selecione_da_lista": "Selecione um cliente na lista.",
            "cliente.erro_ao_excluir": "Problemas ao excluir cliente",
            "cliente.erro_data_invalida": "Data de nascimento inválida. Use o formato DD/MM/AAAA.",
            "cliente.erro_cidade_nao_selecionado": "Selecione uma cidade.",
            "cliente.erro_limite_negativo": "O limite não pode ser negativo.",

            # Tela de Produtos
            "produto.janela_titulo": "CRUD de Produtos",
            "produto.titulo": "Cadastro de Produtos",
            "produto.dados_frame": "Dados do produto",
            "produto.fornecedor": "Fornecedor",
            "produto.estoque": "Estoque",
            "produto.preco": "Preço",
            "produto.valor_estoque": "Valor em estoque",
            "produto.confirmar_exclusao": "Deseja realmente excluir este produto?",
            "produto.cadastrado_sucesso": "Produto cadastrado com sucesso!",
            "produto.atualizado_sucesso": "Produto atualizado com sucesso!",
            "produto.excluido_sucesso": "Produto excluído com sucesso!",
            "produto.nao_encontrado": "Produto não encontrado.",
            "produto.selecione_da_lista": "Selecione um produto na lista.",
            "produto.erro_ao_excluir": "Problemas ao excluir produto",
            "produto.erro_fornecedor_nao_selecionado": "Selecione um fornecedor.",
            "produto.erro_preco_negativo": "O preço não pode ser negativo.",
            "produto.erro_estoque_negativo": "O estoque não pode ser negativo.",

            # Tela de Fornecedores
            "fornecedor.janela_titulo": "CRUD de Fornecedores",
            "fornecedor.titulo": "Cadastro de Fornecedores",
            "fornecedor.dados_frame": "Dados do fornecedor",
            "fornecedor.razao_social": "Razão social",
            "fornecedor.nome_fantasia": "Nome fantasia",
            "fornecedor.cnpj": "CNPJ",
            "fornecedor.sla": "SLA de atendimento",
            "fornecedor.categorias": "Categorias",
            "fornecedor.confirmar_exclusao": "Deseja realmente excluir este fornecedor?",
            "fornecedor.cadastrado_sucesso": "Fornecedor cadastrado com sucesso!",
            "fornecedor.atualizado_sucesso": "Fornecedor atualizado com sucesso!",
            "fornecedor.excluido_sucesso": "Fornecedor excluído com sucesso!",
            "fornecedor.nao_encontrado": "Fornecedor não encontrado.",
            "fornecedor.selecione_da_lista": "Selecione um fornecedor na lista.",
            "fornecedor.erro_ao_excluir": "Problemas ao excluir fornecedor",
            "fornecedor.erro_entrada_invalida": "Entrada inválida. Tente novamente.",
            "fornecedor.erro_sla_negativo": "O SLA de atendimento não pode ser negativo.",
            "fornecedor.sem_categorias": "Cadastre categorias antes de associá-las a um fornecedor.",
            "fornecedor.categorias_atualizadas_sucesso": "Categorias do fornecedor atualizadas com sucesso!",
            "fornecedor.erro_salvar_categorias": "Não foi possível salvar as categorias do fornecedor.",

            #tela de categoria
            "categoria.janela_titulo": "CRUD de categorias",
            "categoria.titulo" : "Cadastro de categoria",
            "categoria.dados_frame" : "Dados da categoria", 
            "categoria.nome" : "Nome",
            "categoria.confirmar_exclusao": "Deseja realmente excluir esta categoria?",
            "categoria.cadastrado_sucesso": "Categoria cadastrada com sucesso!",
            "categoria.atualizado_sucesso": "Categoria atualizada com sucesso!",
            "categoria.excluido_sucesso": "Categoria excluída com sucesso!",
            "categoria.nao_encontrado": "Categoria não encontrada.",
            "categoria.selecione_da_lista": "Selecione uma categoria na lista.",
            "categoria.erro_ao_excluir": "Problemas ao excluir a categoria",
            "categoria.erro_entrada_invalida": "Entrada inválida. Tente novamente.",
            "categoria.cadastro_sucesso" : "Categoria cadastrada com sucesso.",
            
            # Menu principal
            "menu.cadastros_basicos": "Cadastros básicos",
            "menu.estados": "Estados",
            "menu.cidades": "Cidades",
            "menu.acessos": "Acessos",
            "menu.usuarios": "Usuários",
            "menu.perfis": "Perfis",
            "menu.gestao_estoque": "Gestão de estoque",
            "menu.clientes": "Clientes",
            "menu.fornecedores": "Fornecedores",
            "menu.produtos": "Produtos",
            "menu.categorias": "Categorias",
            "menu.idioma": "Idioma",
            "menu.sair": "Sair",
        },
        "en": {

            # Common to several screens
            "comum.id": "ID",
            "comum.nome": "Name",
            "comum.novo": "New",
            "comum.salvar": "Save",
            "comum.alterar": "Edit",
            "comum.excluir": "Delete",
            "comum.fechar": "Close",
            "comum.cancelar": "Cancel",
            "comum.confirmacao": "Confirmation",
            "comum.erro_prefixo": "Error: ",

            # States screen
            "estado.janela_titulo": "State Management",
            "estado.titulo": "State Registration",
            "estado.dados_frame": "State data",
            "estado.sigla": "Abbreviation",
            "estado.confirmar_exclusao": "Do you really want to delete this state?",
            "estado.cadastrado_sucesso": "State registered successfully!",
            "estado.atualizado_sucesso": "State updated successfully!",
            "estado.excluido_sucesso": "State deleted successfully!",
            "estado.nao_encontrado": "State not found.",
            "estado.selecione_da_lista": "Select a state from the list.",
            "estado.erro_ao_excluir": "Problem deleting state",
            "estado.erro_sigla_tamanho": "The abbreviation must have exactly 2 characters.",

            # Cities screen
            "cidade.janela_titulo": "City Management",
            "cidade.titulo": "City Registration",
            "cidade.dados_frame": "City data",
            "cidade.estado": "State",
            "cidade.nome": "Name",
            "cidade.confirmar_exclusao": "Do you really want to delete this city?",
            "cidade.cadastrado_sucesso": "City registered successfully!",
            "cidade.atualizado_sucesso": "City updated successfully!",
            "cidade.excluido_sucesso": "City deleted successfully!",
            "cidade.nao_encontrado": "City not found.",
            "cidade.selecione_da_lista": "Select a city from the list.",
            "cidade.erro_ao_excluir": "Problem deleting city",
            "cidade.erro_nome_vazio": "The city name cannot be empty.",
            "cidade.erro_estado_nao_selecionado": "Select a state for the city.",

            # Users screen
            "usuario.janela_titulo": "User Management",
            "usuario.titulo": "User Registration",
            "usuario.dados_frame": "User data",
            "usuario.nome": "Name",
            "usuario.email": "Email",
            "usuario.nascimento": "Date of birth",
            "usuario.idade": "Age",
            "usuario.cidade": "City",
            "usuario.uf": "State",
            "usuario.perfil": "Role",
            "usuario.erro_cidade_nao_selecionado": "Select a city for the user.",
            "usuario.erro_estado_nao_selecionado": "Select a state for the user.",
            "usuario.erro_perfil_nao_selecionado": "Select a role for the user.",
            "usuario.erro_data_invalida": "Invalid date of birth. Use the DD/MM/YYYY format.",
            "usuario.confirmar_exclusao": "Do you really want to delete this user?",
            "usuario.cadastrado_sucesso": "User registered successfully!",
            "usuario.atualizado_sucesso": "User updated successfully!",
            "usuario.excluido_sucesso": "User deleted successfully!",
            "usuario.nao_encontrado": "User not found.",
            "usuario.selecione_da_lista": "Select a user from the list.",
            "usuario.erro_ao_excluir": "Problem deleting user",
            "usuario.erro_nome_vazio": "The user name cannot be empty.",
            "usuario.erro_email_vazio": "The user email cannot be empty.",

            # Roles screen
            "perfil.janela_titulo": "Role Management",
            "perfil.titulo": "Role Registration",
            "perfil.dados_frame": "Role data",
            "perfil.descricao": "Description",
            "perfil.fornecedores": "Suppliers",
            "perfil.confirmar_exclusao": "Do you really want to delete this role?",
            "perfil.cadastrado_sucesso": "Role registered successfully!",
            "perfil.atualizado_sucesso": "Role updated successfully!",
            "perfil.excluido_sucesso": "Role deleted successfully!",
            "perfil.nao_encontrado": "Role not found.",
            "perfil.selecione_da_lista": "Select a role from the list.",
            "perfil.erro_ao_excluir": "Problem deleting role",
            "perfil.sem_fornecedores": "Register suppliers before assigning them to a role.",
            "perfil.fornecedores_atualizados_sucesso": "Role suppliers updated successfully!",
            "perfil.erro_salvar_fornecedores": "Could not save the role's suppliers.",

            # Customers screen
            "cliente.janela_titulo": "Customer Management",
            "cliente.titulo": "Customer Registration",
            "cliente.dados_frame": "Customer data",
            "cliente.nascimento": "Date of birth",
            "cliente.idade": "Age",
            "cliente.limite_credito": "Credit limit",
            "cliente.cidade": "City",
            "cliente.uf": "State",
            "cliente.confirmar_exclusao": "Do you really want to delete this customer?",
            "cliente.cadastrado_sucesso": "Customer registered successfully!",
            "cliente.atualizado_sucesso": "Customer updated successfully!",
            "cliente.excluido_sucesso": "Customer deleted successfully!",
            "cliente.nao_encontrado": "Customer not found.",
            "cliente.selecione_da_lista": "Select a customer from the list.",
            "cliente.erro_ao_excluir": "Problem deleting customer",
            "cliente.erro_data_invalida": "Invalid date of birth. Use the DD/MM/YYYY format.",
            "cliente.erro_cidade_nao_selecionado": "Select a city.",
            "cliente.erro_limite_negativo": "The limit cannot be negative.",

            # Products screen
            "produto.janela_titulo": "Product Management",
            "produto.titulo": "Product Registration",
            "produto.dados_frame": "Product data",
            "produto.fornecedor": "Supplier",
            "produto.estoque": "Stock",
            "produto.preco": "Price",
            "produto.valor_estoque": "Stock value",
            "produto.confirmar_exclusao": "Do you really want to delete this product?",
            "produto.cadastrado_sucesso": "Product registered successfully!",
            "produto.atualizado_sucesso": "Product updated successfully!",
            "produto.excluido_sucesso": "Product deleted successfully!",
            "produto.nao_encontrado": "Product not found.",
            "produto.selecione_da_lista": "Select a product from the list.",
            "produto.erro_ao_excluir": "Problem deleting product",
            "produto.erro_fornecedor_nao_selecionado": "Select a supplier.",
            "produto.erro_preco_negativo": "The price cannot be negative.",
            "produto.erro_estoque_negativo": "The stock cannot be negative.",

            # Suppliers screen
            "fornecedor.janela_titulo": "Supplier Management",
            "fornecedor.titulo": "Supplier Registration",
            "fornecedor.dados_frame": "Supplier data",
            "fornecedor.razao_social": "Legal name",
            "fornecedor.nome_fantasia": "Trade name",
            "fornecedor.cnpj": "Tax ID",
            "fornecedor.sla": "Service SLA",
            "fornecedor.categorias": "Categories",
            "fornecedor.confirmar_exclusao": "Do you really want to delete this supplier?",
            "fornecedor.cadastrado_sucesso": "Supplier registered successfully!",
            "fornecedor.atualizado_sucesso": "Supplier updated successfully!",
            "fornecedor.excluido_sucesso": "Supplier deleted successfully!",
            "fornecedor.nao_encontrado": "Supplier not found.",
            "fornecedor.selecione_da_lista": "Select a supplier from the list.",
            "fornecedor.erro_ao_excluir": "Problem deleting supplier",
            "fornecedor.erro_entrada_invalida": "Invalid input. Please try again.",
            "fornecedor.erro_sla_negativo": "The service SLA cannot be negative.",
            "fornecedor.sem_categorias": "Register categories before assigning them to a supplier.",
            "fornecedor.categorias_atualizadas_sucesso": "Supplier categories updated successfully!",
            "fornecedor.erro_salvar_categorias": "Could not save the supplier's categories.",

            #category screen
            "categoria.janela_titulo": "Category CRUD",
            "categoria.titulo": "Category Registration",
            "categoria.dados_frame": "Category Data",
            "categoria.nome": "Name",
            "categoria.confirmar_exclusao": "Do you really want to delete this category?",
            "categoria.cadastrado_sucesso": "Category registered successfully!",
            "categoria.atualizado_sucesso": "Category updated successfully!",
            "categoria.excluido_sucesso": "Category deleted successfully!",
            "categoria.nao_encontrado": "Category not found.",
            "categoria.selecione_da_lista": "Select a category from the list.",
            "categoria.erro_ao_excluir": "Problems deleting the category",
            "categoria.erro_entrada_invalida": "Invalid input. Please try again.",
            "categoria.cadastro_sucesso": "Category registered successfully.",

            # Main menu
            "menu.cadastros_basicos": "Basic registrations",
            "menu.estados": "States",
            "menu.cidades": "Cities",
            "menu.acessos": "Access",
            "menu.usuarios": "Users",
            "menu.perfis": "Roles",
            "menu.gestao_estoque": "Inventory management",
            "menu.clientes": "Customers",
            "menu.fornecedores": "Suppliers",
            "menu.produtos": "Products",
            "menu.categorias": "Categories",
            "menu.idioma": "Language",
            "menu.sair": "Exit",
        }
    }

    @classmethod
    def definir(cls, codigo):
        cls.ATUAL = codigo

    @classmethod
    def t(cls, chave):
        return cls.TEXTOS[cls.ATUAL].get(chave, chave)
    